version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    networks:
      - default
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changethis
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:5050"
    environment:
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DEFAULT_EMAIL=admin@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=changethis
    networks:
    - default
  backend:
    build: ./backend
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    networks:
    - default
    depends_on:
      - postgres
  frontend:
    build: ./frontend/app
    ports:
       - "80:80"
    networks:
    - default
volumes:
  postgres:
    driver: local
