"""testfromfastapi5

Revision ID: 50e07d1dbbaa
Revises: d3ecd847c47b
Create Date: 2022-02-18 13:50:26.239959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e07d1dbbaa'
down_revision = 'd3ecd847c47b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
