"""testfromfastapi4

Revision ID: d3ecd847c47b
Revises: 7e68041b4480
Create Date: 2022-02-18 13:47:03.004621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ecd847c47b'
down_revision = '7e68041b4480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
