"""testfromfastapi6

Revision ID: 07ccaa75b92b
Revises: 50e07d1dbbaa
Create Date: 2022-02-18 14:26:06.117973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ccaa75b92b'
down_revision = '50e07d1dbbaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
