"""testfromfastapi8

Revision ID: 953431fcd0cb
Revises: 368a17eedcbb
Create Date: 2022-02-18 15:06:15.171542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953431fcd0cb'
down_revision = '368a17eedcbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
